//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoMessenger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptoMessenger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВХОД В ДАННЫЙ АККАУНТ УЖЕ ВЫПОЛНЕН .
        /// </summary>
        public static string ALREADY_LOGIN_NOTIFICATION {
            get {
                return ResourceManager.GetString("ALREADY_LOGIN_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRYPTO MESSENGER.
        /// </summary>
        public static string APP_NAME {
            get {
                return ResourceManager.GetString("APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НЕ УДАЕТСЯ НАЙТИ СЕРТИФИКАТ ПРИЛОЖЕНИЯ.
        /// </summary>
        public static string CERTIFICATE_ERROR_NOTIFICATION {
            get {
                return ResourceManager.GetString("CERTIFICATE_ERROR_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap envelope {
            get {
                object obj = ResourceManager.GetObject("envelope", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НЕКОРРЕКТНЫЕ ДАННЫЕ.
        /// </summary>
        public static string INCORRECT_DATA_NOTIFICATION {
            get {
                return ResourceManager.GetString("INCORRECT_DATA_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap login {
            get {
                object obj = ResourceManager.GetObject("login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВХОД.
        /// </summary>
        public static string LOGIN_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НЕВЕРНАЯ КОМБИНАЦИЯ ЛОГИНА И ПАРОЛЯ.
        /// </summary>
        public static string LOGIN_ERROR_NOTIFICATION {
            get {
                return ResourceManager.GetString("LOGIN_ERROR_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВХОД....
        /// </summary>
        public static string LOGIN_NOTIFICATION {
            get {
                return ResourceManager.GetString("LOGIN_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СКРЫВАТЬ ПАРОЛЬ.
        /// </summary>
        public static string PASSWORD_CHECKBOX_TEXT {
            get {
                return ResourceManager.GetString("PASSWORD_CHECKBOX_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RainTungsten {
            get {
                object obj = ResourceManager.GetObject("RainTungsten", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap register {
            get {
                object obj = ResourceManager.GetObject("register", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РЕГИСТРАЦИЯ.
        /// </summary>
        public static string REGISTRATION_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("REGISTRATION_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АККАУНТ С ДАННЫМ ЛОГИНОМ УЖЕ ЗАРЕГИСТРИРОВАН.
        /// </summary>
        public static string REGISTRATION_ERROR_NOTIFICATION {
            get {
                return ResourceManager.GetString("REGISTRATION_ERROR_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РЕГИСТРАЦИЯ....
        /// </summary>
        public static string REGISTRATION_NOTIFICATION {
            get {
                return ResourceManager.GetString("REGISTRATION_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВЫ УСПЕШНО ЗАРЕГИСТРИРОВАЛИСЬ.
        /// </summary>
        public static string REGISTRATION_SUCCESS_NOTIFICATION {
            get {
                return ResourceManager.GetString("REGISTRATION_SUCCESS_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НЕ УДАЕТСЯ ПОДКЛЮЧИТЬСЯ К СЕРВЕРУ.
        /// </summary>
        public static string SERVER_CONNECTION_ERROR_NOTIFICATION {
            get {
                return ResourceManager.GetString("SERVER_CONNECTION_ERROR_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДОБРО ПОЖАЛОВАТЬ.
        /// </summary>
        public static string STANDART_NOTIFICATION {
            get {
                return ResourceManager.GetString("STANDART_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НЕИЗВЕСТНАЯ ОШИБКА. ПОВТОРИТЕ ДЕЙСТВИЕ ПОЗЖЕ.
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЛОГИН.
        /// </summary>
        public static string USERNAME_TEXTFIELD_PLACEHOLDER {
            get {
                return ResourceManager.GetString("USERNAME_TEXTFIELD_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПАРОЛЬ.
        /// </summary>
        public static string USERPASSWORD_TEXTFIELD_PLACEHOLDER {
            get {
                return ResourceManager.GetString("USERPASSWORD_TEXTFIELD_PLACEHOLDER", resourceCulture);
            }
        }
    }
}
