//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoMessenger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptoMessenger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принять заявку.
        /// </summary>
        public static string ACCEPTFRIENDSHIP_BUTTON_TOOLTIP {
            get {
                return ResourceManager.GetString("ACCEPTFRIENDSHIP_BUTTON_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить в друзья.
        /// </summary>
        public static string ADDTOFRIENDS_BUTTON_TOOLTIP {
            get {
                return ResourceManager.GetString("ADDTOFRIENDS_BUTTON_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в данный аккаунт уже выполнен.
        /// </summary>
        public static string ALREADY_LOGIN_NOTIFICATION {
            get {
                return ResourceManager.GetString("ALREADY_LOGIN_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRYPTO MESSENGER.
        /// </summary>
        public static string APP_NAME {
            get {
                return ResourceManager.GetString("APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить заявку.
        /// </summary>
        public static string CANCELREQUEST_BUTTON_TOOLTIP {
            get {
                return ResourceManager.GetString("CANCELREQUEST_BUTTON_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается найти сертификат приложения. Переустановка может исправить проблему.
        /// </summary>
        public static string CERTIFICATE_ERROR_NOTIFICATION {
            get {
                return ResourceManager.GetString("CERTIFICATE_ERROR_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друзей нет.
        /// </summary>
        public static string EMPTY_FRIENDS_LIST_PLACEHOLDER {
            get {
                return ResourceManager.GetString("EMPTY_FRIENDS_LIST_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявок нет.
        /// </summary>
        public static string EMPTY_REQUESTS_LIST_PLACEHOLDER {
            get {
                return ResourceManager.GetString("EMPTY_REQUESTS_LIST_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователей не найдено.
        /// </summary>
        public static string EMPTY_USERS_LIST_PLACEHOLDER {
            get {
                return ResourceManager.GetString("EMPTY_USERS_LIST_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap envelope {
            get {
                object obj = ResourceManager.GetObject("envelope", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДРУЗЬЯ.
        /// </summary>
        public static string FRIENDSS_TEXTBLOCK_TEXT {
            get {
                return ResourceManager.GetString("FRIENDSS_TEXTBLOCK_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявки вам:.
        /// </summary>
        public static string INCOME_REQUESTS_TEXTBLOCK_TEXT {
            get {
                return ResourceManager.GetString("INCOME_REQUESTS_TEXTBLOCK_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректные данные.
        /// </summary>
        public static string INCORRECT_DATA_NOTIFICATION {
            get {
                return ResourceManager.GetString("INCORRECT_DATA_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap login {
            get {
                object obj = ResourceManager.GetObject("login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВХОД.
        /// </summary>
        public static string LOGIN_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверная комбинация логина и пароля.
        /// </summary>
        public static string LOGIN_ERROR_NOTIFICATION {
            get {
                return ResourceManager.GetString("LOGIN_ERROR_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход. Пожалуйста, подождите....
        /// </summary>
        public static string LOGIN_NOTIFICATION {
            get {
                return ResourceManager.GetString("LOGIN_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Ваше сообщение здесь....
        /// </summary>
        public static string MESSAGE_TEXTBOX_PLACEHOLDER {
            get {
                return ResourceManager.GetString("MESSAGE_TEXTBOX_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваши заявки:.
        /// </summary>
        public static string OUTCOME_REQUESTS_TEXTBLOCK_TEXT {
            get {
                return ResourceManager.GetString("OUTCOME_REQUESTS_TEXTBLOCK_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СКРЫВАТЬ ПАРОЛЬ.
        /// </summary>
        public static string PASSWORD_CHECKBOX_TEXT {
            get {
                return ResourceManager.GetString("PASSWORD_CHECKBOX_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RainTungsten {
            get {
                object obj = ResourceManager.GetObject("RainTungsten", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap register {
            get {
                object obj = ResourceManager.GetObject("register", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РЕГИСТРАЦИЯ.
        /// </summary>
        public static string REGISTRATION_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("REGISTRATION_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт с данным логином уже зарегистрирован.
        /// </summary>
        public static string REGISTRATION_ERROR_NOTIFICATION {
            get {
                return ResourceManager.GetString("REGISTRATION_ERROR_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация. Пожалуйста, подождите....
        /// </summary>
        public static string REGISTRATION_NOTIFICATION {
            get {
                return ResourceManager.GetString("REGISTRATION_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы успешно зарегистрировались.
        /// </summary>
        public static string REGISTRATION_SUCCESS_NOTIFICATION {
            get {
                return ResourceManager.GetString("REGISTRATION_SUCCESS_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отклонить заявку.
        /// </summary>
        public static string REJECTFRIENDSHIP_BUTTON_TOOLTIP {
            get {
                return ResourceManager.GetString("REJECTFRIENDSHIP_BUTTON_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить из друзей.
        /// </summary>
        public static string REMOVE_BUTTON_TOOLTIP {
            get {
                return ResourceManager.GetString("REMOVE_BUTTON_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЗАЯВКИ.
        /// </summary>
        public static string REQUESTS_TEXTBLOCK_TEXT {
            get {
                return ResourceManager.GetString("REQUESTS_TEXTBLOCK_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПОИСК.
        /// </summary>
        public static string SEARCH_TEXTBLOCK_TEXT {
            get {
                return ResourceManager.GetString("SEARCH_TEXTBLOCK_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы начать диалог, выберите друга из списка друзей слева.
        /// </summary>
        public static string SELECT_FRIEND_NOTIFICATION {
            get {
                return ResourceManager.GetString("SELECT_FRIEND_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается подключиться к серверу.
        /// </summary>
        public static string SERVER_CONNECTION_ERROR_NOTIFICATION {
            get {
                return ResourceManager.GetString("SERVER_CONNECTION_ERROR_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать.
        /// </summary>
        public static string STANDART_NOTIFICATION {
            get {
                return ResourceManager.GetString("STANDART_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная ошибка. Повторите действие позже.
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЛОГИН.
        /// </summary>
        public static string USERNAME_TEXTFIELD_PLACEHOLDER {
            get {
                return ResourceManager.GetString("USERNAME_TEXTFIELD_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПАРОЛЬ.
        /// </summary>
        public static string USERPASSWORD_TEXTFIELD_PLACEHOLDER {
            get {
                return ResourceManager.GetString("USERPASSWORD_TEXTFIELD_PLACEHOLDER", resourceCulture);
            }
        }
    }
}
