//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoMessenger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptoMessenger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принять заявку.
        /// </summary>
        public static string AcceptFriendshipButtonTooltip {
            get {
                return ResourceManager.GetString("AcceptFriendshipButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить в друзья.
        /// </summary>
        public static string AddToFriendsButtonTooltip {
            get {
                return ResourceManager.GetString("AddToFriendsButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в данный аккаунт уже выполнен.
        /// </summary>
        public static string AlreadyLoginNotification {
            get {
                return ResourceManager.GetString("AlreadyLoginNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto Messenger.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить заявку.
        /// </summary>
        public static string CancelRequestButtonTooltip {
            get {
                return ResourceManager.GetString("CancelRequestButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается найти сертификат приложения. Переустановка может исправить проблему.
        /// </summary>
        public static string CertificateErrorNotification {
            get {
                return ResourceManager.GetString("CertificateErrorNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соединение с сервером разорвано. Вы можете не выходить из приложения, чтобы иметь доступ к загруженным сообщениям.
        /// </summary>
        public static string ConnectionBreaksNotification {
            get {
                return ResourceManager.GetString("ConnectionBreaksNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается подключиться к серверу.
        /// </summary>
        public static string ConnectionErrorNotification {
            get {
                return ResourceManager.GetString("ConnectionErrorNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите логин и пароль.
        /// </summary>
        public static string EmptyDataNotification {
            get {
                return ResourceManager.GetString("EmptyDataNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщений нет.
        /// </summary>
        public static string EmptyDialogListboxPlaceholder {
            get {
                return ResourceManager.GetString("EmptyDialogListboxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друзей нет.
        /// </summary>
        public static string EmptyFriendsListboxPlaceholder {
            get {
                return ResourceManager.GetString("EmptyFriendsListboxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявок нет.
        /// </summary>
        public static string EmptyRequestsListboxPlaceholder {
            get {
                return ResourceManager.GetString("EmptyRequestsListboxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователей не найдено.
        /// </summary>
        public static string EmptyUsersListboxPlaceholder {
            get {
                return ResourceManager.GetString("EmptyUsersListboxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap envelope {
            get {
                object obj = ResourceManager.GetObject("envelope", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход из аккаунта.
        /// </summary>
        public static string ExitButtonText {
            get {
                return ResourceManager.GetString("ExitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДРУЗЬЯ.
        /// </summary>
        public static string FriendsTextboxText {
            get {
                return ResourceManager.GetString("FriendsTextboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявки вам:.
        /// </summary>
        public static string IncomeRequestsTextblockText {
            get {
                return ResourceManager.GetString("IncomeRequestsTextblockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин и пароль должны состоять только из английских символов и цифр.
        /// </summary>
        public static string IncorrectDataNotification {
            get {
                return ResourceManager.GetString("IncorrectDataNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap login {
            get {
                object obj = ResourceManager.GetObject("login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginButtonText {
            get {
                return ResourceManager.GetString("LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверная комбинация логина и пароля.
        /// </summary>
        public static string LoginErrorNotification {
            get {
                return ResourceManager.GetString("LoginErrorNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход. Пожалуйста, подождите....
        /// </summary>
        public static string LoginNotification {
            get {
                return ResourceManager.GetString("LoginNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Enter&gt; - отправить, &lt;Shift&gt;+&lt;Enter&gt; - новая строка.
        /// </summary>
        public static string MessageTextboxPlaceholder {
            get {
                return ResourceManager.GetString("MessageTextboxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ок.
        /// </summary>
        public static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваши заявки:.
        /// </summary>
        public static string OutcomeRequestsTextblockText {
            get {
                return ResourceManager.GetString("OutcomeRequestsTextblockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap register {
            get {
                object obj = ResourceManager.GetObject("register", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string RegistrationButtonText {
            get {
                return ResourceManager.GetString("RegistrationButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт с данным логином уже зарегистрирован.
        /// </summary>
        public static string RegistrationErrorNotification {
            get {
                return ResourceManager.GetString("RegistrationErrorNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация. Пожалуйста, подождите....
        /// </summary>
        public static string RegistrationNotification {
            get {
                return ResourceManager.GetString("RegistrationNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы успешно зарегистрировались.
        /// </summary>
        public static string RegistrationSuccessNotification {
            get {
                return ResourceManager.GetString("RegistrationSuccessNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отклонить заявку.
        /// </summary>
        public static string RejectFriendshipButtonTooltip {
            get {
                return ResourceManager.GetString("RejectFriendshipButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить из друзей.
        /// </summary>
        public static string RemoveFriendButtonTooltip {
            get {
                return ResourceManager.GetString("RemoveFriendButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЗАЯВКИ.
        /// </summary>
        public static string RequestTextblockText {
            get {
                return ResourceManager.GetString("RequestTextblockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RobotoCondensed_Bold {
            get {
                object obj = ResourceManager.GetObject("RobotoCondensed_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПОИСК.
        /// </summary>
        public static string SearchTextblockText {
            get {
                return ResourceManager.GetString("SearchTextblockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы начать диалог, выберите друга из списка друзей слева.
        /// </summary>
        public static string SelectFriendNotification {
            get {
                return ResourceManager.GetString("SelectFriendNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap send {
            get {
                object obj = ResourceManager.GetObject("send", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить сообщение.
        /// </summary>
        public static string SendMessageButtonTooltip {
            get {
                return ResourceManager.GetString("SendMessageButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оффлайн.
        /// </summary>
        public static string StatusOfflineText {
            get {
                return ResourceManager.GetString("StatusOfflineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Онлайн.
        /// </summary>
        public static string StatusOnlineText {
            get {
                return ResourceManager.GetString("StatusOnlineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная ошибка. Повторите действие позже.
        /// </summary>
        public static string UnknownErrorNotification {
            get {
                return ResourceManager.GetString("UnknownErrorNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string UsernameTextboxPlaceholder {
            get {
                return ResourceManager.GetString("UsernameTextboxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string UserPasswordTextboxPlaceholder {
            get {
                return ResourceManager.GetString("UserPasswordTextboxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать.
        /// </summary>
        public static string WelcomeNotification {
            get {
                return ResourceManager.GetString("WelcomeNotification", resourceCulture);
            }
        }
    }
}
