//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoMessenger.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF4C4743")]
        public global::System.Windows.Media.SolidColorBrush MainFirstBrush {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["MainFirstBrush"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF818181")]
        public global::System.Windows.Media.SolidColorBrush MainSecondBrush {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["MainSecondBrush"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFEC606")]
        public global::System.Windows.Media.SolidColorBrush SpecialBrush {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["SpecialBrush"]));
            }
            set {
                this["SpecialBrush"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF959590")]
        public global::System.Windows.Media.SolidColorBrush MainSecondLightBrush {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["MainSecondLightBrush"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public global::System.Windows.Media.SolidColorBrush AlertBrush {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["AlertBrush"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF00FF00")]
        public global::System.Windows.Media.SolidColorBrush SuccessBrush {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["SuccessBrush"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.SolidColorBrush SecondaryFirstBrush {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["SecondaryFirstBrush"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFDCDCDC")]
        public global::System.Windows.Media.SolidColorBrush SecondarySecondBrush {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["SecondarySecondBrush"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFEC606")]
        public global::System.Windows.Media.Color SpecialColor {
            get {
                return ((global::System.Windows.Media.Color)(this["SpecialColor"]));
            }
            set {
                this["SpecialColor"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public global::System.Windows.Media.Color AlertColor {
            get {
                return ((global::System.Windows.Media.Color)(this["AlertColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF56514D")]
        public global::System.Windows.Media.SolidColorBrush MainFirstLightBrush {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["MainFirstLightBrush"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ActionDelayMsec {
            get {
                return ((int)(this["ActionDelayMsec"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2500")]
        public int HideNotificationDelayMsec {
            get {
                return ((int)(this["HideNotificationDelayMsec"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int WaitServerConnectionDelayMsec {
            get {
                return ((int)(this["WaitServerConnectionDelayMsec"]));
            }
        }
    }
}
